### ISSUE TITLE
Passing options data 

### ISSUE THREAD

**Issue by enki-code** [IonicaBizau/gh.js#11]
I'm attempting to [create a new gist](https://developer.github.com/v3/gists/#create-a-gist), according to the gh.js documentation including my post data in the options object this should work, I keep getting 404 not found though.  

Inspecting the request is showing that my data is not being passed along and the request method is still 'GET'.

Not quite sure what I am doing wrong.

Mind pointing me in the right direction?

```
(function() {
    var gh = new GitHub({
        token: "my-access-token"
    });

    gh.get("gists/", {
            all: false,
            opts: '',
            data: {
                description: 'test',
                public: true,
                files: {
                    'README.MD': {
                        content: 'Content created with gh.js'
                    }
                }
            },
            req_options: '',
            method: 'POST'
        },

        function(err, data) {
            console.clear();
            console.log(err || data.files['README.MD'].content);
        });
})();
```

**Comment by enki-code** [comment]
Apparently it doesn't like the trailing forward slash, 

This works:

```
gh.req("gists", {
    method: 'POST',
    data: {
        description: 'test',
        public: true,
        files: {
             'README.MD':  {
                content: 'Content created with gh.js'
              }
          }
    }
 }, function(err, data) {
  console.log(err || data.files['README.MD'].content);
});
```

**Comment by IonicaBizau** [comment]
@enki-code Oh, yeah... That trailing slash is annoying. Maybe I should throw an error to tell the users that it should be like that (so it's clearer what's going on). :dizzy: 

Sorry for late answer, but I was traveling in the last days.

Reopening and will take care of it. :rocket:
