### ISSUE TITLE
How do I edit a Gist?

### ISSUE THREAD

**Issue by shu8** [IonicaBizau/gh.js#12]
I'm trying to edit a gist. Using [the docs](https://developer.github.com/v3/gists/#edit-a-gist), I'm supposed to `PATCH /gists/:id`, but trying `method: 'PATCH'` only sends a POST!

                               gh.req("gists/gistid", {
                                    method: 'PATCH',
                                    data: {
                                        content: "test"
                                    }
                                }, function(e, d) {
                                    console.log(e || d);
                                });

I get a 404 Not Found error.

Is there a different way to PATCH?

**Comment by enki-code** [comment]
Request is malformed, but it still doesn't work. Keeps returning 404 Not Found.  

Inspecting the network tab in the console confirms the request being made is a POST, not patch, which could be the issue. 

I don't see anything in the source that would be altering the METHOD, but, I could be missing something.


```
(function() {
  var gh = new GitHub({
    token: "access-token"
  });

  gh.req("gists/gist-id", { 
    method: 'PATCH',
    data: {
      description: 'updated description',
      public: true,
      files: {
        'myfile.json': {
          content: 'updated content'
        }
      }
    }
  }, function(err, data) {
    console.log(err || data.files['myfile.json'].content);
  });

})();

```

FYI @IonicaBizau   @shu8 and I are working on a project together using your library. :+1:

**Comment by IonicaBizau** [comment]
> FYI @IonicaBizau; @shu8 and I are working on a project together using your library. :+1:

That's great! :+1: 


I'm checking this right now.

**Comment by enki-code** [comment]
@IonicaBizau   Thank you, we appreciate the quick feedback.  BTW, I forgot to mention in my previous comment, the library is fantastic, simple to use and saved us a ton of time.  We appreciate all the work you put into this.

**Comment by IonicaBizau** [comment]
@enki-code I'm really happy to hear! :grin: I feel like I already fixed this previously but maybe the installed module versions are not the latest. I'm debugging the things. :crystal_ball:

**Comment by enki-code** [comment]
@IonicaBizau  Sorry, we should have specified, we are using version 3.0.3 hosted from cdnjs

`https://cdnjs.cloudflare.com/ajax/libs/gh.js/3.0.3/gh.min.js`

**Comment by IonicaBizau** [comment]
@enki-code That should be fine, because it's anyway the same piece of code bundled for the client.

**Comment by IonicaBizau** [comment]
Not sure why this ends with 404:

```sh
curl -v -X PATCH -d '{"files":{"test":{"content":"test"}}}' https://api.github.com/gists/93ef31c3315a25bba55a6f50bf021dae?access_token=...
```

Any ideas?

**Comment by enki-code** [comment]
I'm not sure either.. I [created a fiddle](https://jsfiddle.net/enkicode/11gj9j97/), that's where we've been testing.

**Comment by IonicaBizau** [comment]
@enki-code Well, I'm not sure about the curl command. In the library, the `method` is clearly broken (it only supports POST and GET). I fixed that locally, but not sure why the `curl` command does not work.

**Comment by IonicaBizau** [comment]
Oh, I found out why: because the `gist` scope was missing from my access token... Going to send a support message to GitHub to show a better error. :grin:

**Comment by enki-code** [comment]
I updated my access token to add the gist scope and I'm getting a BAD CREDENTIALS error now.  Any ideas?

**Comment by IonicaBizau** [comment]
@enki-code I'm pushing the fix on GH in one moment. :hourglass:

**Comment by enki-code** [comment]
@IonicaBizau  Would you mind adding the updated version to the CDN? Thanks again for the quick turn around, you've been a big help.

**Comment by IonicaBizau** [comment]
@enki-code That's happening automagically. :grin:

**Comment by IonicaBizau** [comment]
If I'm not wrong in about 30 minutes... In the meantime, you could use [`https://cdn.rawgit.com/IonicaBizau/gh.js/master/dist/gh.min.js`](https://cdn.rawgit.com/IonicaBizau/gh.js/master/dist/gh.min.js).

**Comment by enki-code** [comment]
Oh, that's great.. I really need to learn how to use require.js and start building out module like you do.  Still don't understand how that all works.

**Comment by IonicaBizau** [comment]
@enki-code Maybe I will write a post about it. :grin:

**Comment by enki-code** [comment]
@IonicaBizau  That would be amazing! :+1:  :smiley:
