### ISSUE TITLE
Issue with authentication

### ISSUE THREAD

**Issue by lpotapczuk** [IonicaBizau/gh.js#4]
Hey!

I have an issue with the library. It seems, that whenever I try to get anything from the GitHub API, it is called using my 60 requests limit, not with my 5000 (which should I get from the auth token, right?).

What I've done, was paste my token from GitHub Personal access tokens (the one with all default scopes). 

Hope you can help me with this one as well :) 

Lukasz

**Comment by lpotapczuk** [comment]
Fixed in the ticket:

https://github.com/IonicaBizau/gh.js/pull/5

 :)

**Comment by IonicaBizau** [comment]
Thanks for fixing it! Also, keep in mind: when you see a `dist` directory, download the file from there, not from the example.

Anyway, nice catch! :sparkle:
